### PR TITLE
Update OAuth2 to 1.1

### PR DESCRIPTION
**Pull request by YoranBrondsema**
For Rack 2 support.

### CODE REVIEW

**Comment by YoranBrondsema** [comment]
After a lot of tries managed to get everything passing.

1. The latest version of Bundler does not work with JRuby 1.8 (see https://github.com/bundler/bundler/issues/4586) so I had to disable that in CI.
2. I fixed the Rubocop offenses.

**Comment by swistaczek** [comment]
👍

**Comment by tgxworld** [comment]
@mbleigh @sferik Is there anything we can do to help get this merged and released? :smile:

**Comment by morgoth** [comment]
Wondering about the same thing :) - Can we have a new release please with this patch?

**Comment by tarun-pacifica** [comment]
Yes please, can we have a new release with this patch asap? It's been more than a year......

**Comment by YoranBrondsema** [comment]
@mbleigh @sferik Is there anything we can do to help get this merged and released?

**Comment by tmilewski** [comment]
Can't push to Rubygems until I gain access. I'm working on that now.

**Pull request merged**
